#!/usr/bin/env bash
# bash script that changes the listening port from 80 to 8080

 # if running, stops nginx
 sudo service nginx stop

 # changes user
 sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

 # changes ownership
 chmod 644 /etc/nginx/nginx.conf

 #chnges the listening port from port 80 to port 8080
  sed -i 's/80/8080/g' /etc/nginx/sites-available/default

 # Kills apache2 incase its running
 pkill apache2
 # this line will start nginx
 sudo -u nginx service nginx start
